name: build image

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Gitea registry
        uses: docker/login-action@v3
        with:
          registry: git.facorazza.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set image tag
        id: image-tag
        run: |
          if [[ ${{ gitea.ref }} == refs/tags/* ]]; then
            echo "IMAGE_TAG=${GITEA_REF#refs/tags/}" >> $GITEA_OUTPUT
          elif [[ ${{ gitea.ref }} == refs/heads/main ]]; then
            echo "IMAGE_TAG=latest" >> $GITEA_OUTPUT
          elif [[ ${{ gitea.ref }} == refs/heads/develop ]]; then
            echo "IMAGE_TAG=develop" >> $GITEA_OUTPUT
          else
            echo "IMAGE_TAG=${GITEA_SHA::8}" >> $GITEA_OUTPUT
          fi
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: git.facorazza.com/facorazza/borgbackup:${{ steps.image-tag.outputs.IMAGE_TAG }}
